-- Payroll module: the monthly run, its lines and money items, the approval chain, and the
-- advances / deductions / cash-allocation registers that feed it.
-- DDL generated by 'prisma migrate diff'; the constraints Prisma cannot express are appended.

-- AlterTable
ALTER TABLE "RewardCase" ADD COLUMN     "paidAt" TIMESTAMP(3),
ADD COLUMN     "paidInRunId" TEXT,
ADD COLUMN     "payoutPeriod" TEXT;

-- CreateTable
CREATE TABLE "PayrollRun" (
    "id" TEXT NOT NULL,
    "runNumber" TEXT NOT NULL,
    "period" TEXT NOT NULL,
    "revision" INTEGER NOT NULL DEFAULT 1,
    "periodStart" TIMESTAMP(3) NOT NULL,
    "periodEnd" TIMESTAMP(3) NOT NULL,
    "cutoffAt" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "stage" TEXT NOT NULL DEFAULT 'PAYROLL_SPECIALIST',
    "lockedAt" TIMESTAMP(3),
    "approvedAt" TIMESTAMP(3),
    "paidAt" TIMESTAMP(3),
    "paymentReference" TEXT,
    "paymentDocumentUrl" TEXT,
    "paymentDocumentName" TEXT,
    "cancelledAt" TIMESTAMP(3),
    "cancelReason" TEXT,
    "calcVersion" INTEGER NOT NULL DEFAULT 1,
    "computingAt" TIMESTAMP(3),
    "attendanceFetchedAt" TIMESTAMP(3),
    "attendanceSourceStart" TEXT,
    "attendanceSourceEnd" TEXT,
    "attendanceRowCount" INTEGER NOT NULL DEFAULT 0,
    "attendanceWarnings" JSONB,
    "approvalDocumentUrl" TEXT,
    "approvalDocumentName" TEXT,
    "notes" TEXT,
    "createdById" TEXT,
    "createdByName" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PayrollRun_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PayrollLine" (
    "id" TEXT NOT NULL,
    "runId" TEXT NOT NULL,
    "employeeId" TEXT,
    "staffId" TEXT,
    "fullName" TEXT,
    "fullNameArabic" TEXT,
    "divisionName" TEXT,
    "departmentName" TEXT,
    "unitName" TEXT,
    "positionTitle" TEXT,
    "workLocation" TEXT,
    "bankName" TEXT,
    "bankAccountNumber" TEXT,
    "contractEndDate" TIMESTAMP(3),
    "residencyType" TEXT,
    "jobCategory" TEXT,
    "jobGrade" TEXT,
    "structureLevel" TEXT,
    "currency" TEXT NOT NULL DEFAULT 'LYD',
    "hourlyRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "positionFactor" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "siteFactor" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "skillFactor" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "languageFactor" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "factorF" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "attendanceMatched" BOOLEAN NOT NULL DEFAULT false,
    "empCode" TEXT,
    "workMins" INTEGER NOT NULL DEFAULT 0,
    "otMins" INTEGER NOT NULL DEFAULT 0,
    "approvedOtMins" INTEGER NOT NULL DEFAULT 0,
    "paidLeaveMins" INTEGER NOT NULL DEFAULT 0,
    "unpaidLeaveMins" INTEGER NOT NULL DEFAULT 0,
    "lateMins" INTEGER NOT NULL DEFAULT 0,
    "earlyOutMins" INTEGER NOT NULL DEFAULT 0,
    "absenceDays" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "suspensionDays" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "attendanceRaw" JSONB,
    "basicHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "overtimeHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "totalWorkingHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "paidAbsenceHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "unpaidHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "basicSalary" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "positionAllowance" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "siteAllowance" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "languageAllowance" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "skillAllowance" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "paidAbsenceAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "bonusPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "bonusAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "totalEarnings" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "deductionsTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "netSalary" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "remainingAdvanceBalance" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "serviceProviderId" TEXT,
    "serviceProviderName" TEXT,
    "serviceProviderPercentage" DOUBLE PRECISION,
    "serviceProviderFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "employerTotalCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "presenceScore" DOUBLE PRECISION,
    "execScore" DOUBLE PRECISION,
    "adminScore" DOUBLE PRECISION,
    "careScore" DOUBLE PRECISION,
    "trainingScore" DOUBLE PRECISION,
    "evaluationTotal" DOUBLE PRECISION,
    "promotionEligibilityIndex" DOUBLE PRECISION,
    "paidLeaveBalance" DOUBLE PRECISION,
    "unpaidLeaveBalance" DOUBLE PRECISION,
    "emergencyLeaveBalance" DOUBLE PRECISION,
    "status" TEXT NOT NULL DEFAULT 'OK',
    "blockReasons" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "excludeReason" TEXT,
    "reviewNote" TEXT,
    "payslipUrl" TEXT,
    "payslipName" TEXT,
    "payslipGeneratedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PayrollLine_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PayrollLineItem" (
    "id" TEXT NOT NULL,
    "lineId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "labelArabic" TEXT,
    "amount" DOUBLE PRECISION NOT NULL,
    "currency" TEXT NOT NULL,
    "percent" DOUBLE PRECISION,
    "sourceType" TEXT,
    "sourceId" TEXT,
    "advanceInstalmentId" TEXT,
    "rewardCaseId" TEXT,
    "correctedRunId" TEXT,
    "correctedLineId" TEXT,
    "correctionNote" TEXT,
    "createdByName" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PayrollLineItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PayrollLineOverride" (
    "id" TEXT NOT NULL,
    "runId" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "excluded" BOOLEAN NOT NULL DEFAULT false,
    "excludeReason" TEXT,
    "reviewNote" TEXT,
    "manualItems" JSONB,
    "createdByName" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PayrollLineOverride_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PayrollRunTotal" (
    "id" TEXT NOT NULL,
    "runId" TEXT NOT NULL,
    "currency" TEXT NOT NULL,
    "residencyType" TEXT NOT NULL DEFAULT 'ALL',
    "employeeCount" INTEGER NOT NULL DEFAULT 0,
    "basicTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "allowanceTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "paidLeaveTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "bonusTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "deductionTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "netTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "serviceProviderFeeTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "employerCostTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,

    CONSTRAINT "PayrollRunTotal_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PayrollApprovalStep" (
    "id" TEXT NOT NULL,
    "runId" TEXT NOT NULL,
    "sequence" INTEGER NOT NULL,
    "stage" TEXT NOT NULL,
    "approverUserId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "note" TEXT,
    "decidedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PayrollApprovalStep_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EmployeeAdvance" (
    "id" TEXT NOT NULL,
    "requestNumber" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'SALARY_ADVANCE',
    "currency" TEXT NOT NULL,
    "principal" DOUBLE PRECISION NOT NULL,
    "instalmentCount" INTEGER NOT NULL DEFAULT 1,
    "firstDeductionPeriod" TEXT NOT NULL,
    "outstandingAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "reason" TEXT,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "approvedAt" TIMESTAMP(3),
    "approvedByName" TEXT,
    "rejectedAt" TIMESTAMP(3),
    "rejectionReason" TEXT,
    "disbursedAt" TIMESTAMP(3),
    "settledAt" TIMESTAMP(3),
    "documentUrl" TEXT,
    "documentName" TEXT,
    "notes" TEXT,
    "createdByName" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EmployeeAdvance_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EmployeeAdvanceInstalment" (
    "id" TEXT NOT NULL,
    "advanceId" TEXT NOT NULL,
    "sequence" INTEGER NOT NULL,
    "period" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'SCHEDULED',
    "deductedInRunId" TEXT,
    "deductedAt" TIMESTAMP(3),
    "note" TEXT,

    CONSTRAINT "EmployeeAdvanceInstalment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EmployeeDeduction" (
    "id" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "labelArabic" TEXT,
    "currency" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "period" TEXT,
    "recurring" BOOLEAN NOT NULL DEFAULT false,
    "startPeriod" TEXT,
    "endPeriod" TEXT,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "approvedAt" TIMESTAMP(3),
    "approvedByName" TEXT,
    "appliedInRunId" TEXT,
    "documentUrl" TEXT,
    "documentName" TEXT,
    "notes" TEXT,
    "createdByName" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EmployeeDeduction_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CashAllocationRequest" (
    "id" TEXT NOT NULL,
    "requestNumber" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "serviceProviderId" TEXT,
    "purpose" TEXT,
    "currency" TEXT NOT NULL,
    "amountRequested" DOUBLE PRECISION NOT NULL,
    "amountApproved" DOUBLE PRECISION,
    "neededBy" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'SUBMITTED',
    "approvedAt" TIMESTAMP(3),
    "approvedByName" TEXT,
    "rejectedAt" TIMESTAMP(3),
    "rejectionReason" TEXT,
    "disbursedAt" TIMESTAMP(3),
    "liquidatedAt" TIMESTAMP(3),
    "amountLiquidated" DOUBLE PRECISION,
    "amountToRecover" DOUBLE PRECISION,
    "recoveryPeriod" TEXT,
    "recoveredInRunId" TEXT,
    "documentUrl" TEXT,
    "documentName" TEXT,
    "notes" TEXT,
    "createdByName" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CashAllocationRequest_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "PayrollRun_runNumber_key" ON "PayrollRun"("runNumber");

-- CreateIndex
CREATE INDEX "PayrollRun_status_idx" ON "PayrollRun"("status");

-- CreateIndex
CREATE INDEX "PayrollRun_period_idx" ON "PayrollRun"("period");

-- CreateIndex
CREATE UNIQUE INDEX "PayrollRun_period_revision_key" ON "PayrollRun"("period", "revision");

-- CreateIndex
CREATE INDEX "PayrollLine_runId_status_idx" ON "PayrollLine"("runId", "status");

-- CreateIndex
CREATE INDEX "PayrollLine_runId_currency_idx" ON "PayrollLine"("runId", "currency");

-- CreateIndex
CREATE INDEX "PayrollLine_employeeId_idx" ON "PayrollLine"("employeeId");

-- CreateIndex
CREATE UNIQUE INDEX "PayrollLine_runId_employeeId_key" ON "PayrollLine"("runId", "employeeId");

-- CreateIndex
CREATE UNIQUE INDEX "PayrollLineItem_advanceInstalmentId_key" ON "PayrollLineItem"("advanceInstalmentId");

-- CreateIndex
CREATE UNIQUE INDEX "PayrollLineItem_rewardCaseId_key" ON "PayrollLineItem"("rewardCaseId");

-- CreateIndex
CREATE INDEX "PayrollLineItem_lineId_idx" ON "PayrollLineItem"("lineId");

-- CreateIndex
CREATE INDEX "PayrollLineItem_category_idx" ON "PayrollLineItem"("category");

-- CreateIndex
CREATE UNIQUE INDEX "PayrollLineOverride_runId_employeeId_key" ON "PayrollLineOverride"("runId", "employeeId");

-- CreateIndex
CREATE UNIQUE INDEX "PayrollRunTotal_runId_currency_residencyType_key" ON "PayrollRunTotal"("runId", "currency", "residencyType");

-- CreateIndex
CREATE INDEX "PayrollApprovalStep_runId_idx" ON "PayrollApprovalStep"("runId");

-- CreateIndex
CREATE INDEX "PayrollApprovalStep_approverUserId_status_idx" ON "PayrollApprovalStep"("approverUserId", "status");

-- CreateIndex
CREATE UNIQUE INDEX "PayrollApprovalStep_runId_sequence_approverUserId_key" ON "PayrollApprovalStep"("runId", "sequence", "approverUserId");

-- CreateIndex
CREATE UNIQUE INDEX "EmployeeAdvance_requestNumber_key" ON "EmployeeAdvance"("requestNumber");

-- CreateIndex
CREATE INDEX "EmployeeAdvance_employeeId_status_idx" ON "EmployeeAdvance"("employeeId", "status");

-- CreateIndex
CREATE INDEX "EmployeeAdvanceInstalment_period_status_idx" ON "EmployeeAdvanceInstalment"("period", "status");

-- CreateIndex
CREATE UNIQUE INDEX "EmployeeAdvanceInstalment_advanceId_sequence_key" ON "EmployeeAdvanceInstalment"("advanceId", "sequence");

-- CreateIndex
CREATE INDEX "EmployeeDeduction_employeeId_status_idx" ON "EmployeeDeduction"("employeeId", "status");

-- CreateIndex
CREATE INDEX "EmployeeDeduction_period_idx" ON "EmployeeDeduction"("period");

-- CreateIndex
CREATE UNIQUE INDEX "CashAllocationRequest_requestNumber_key" ON "CashAllocationRequest"("requestNumber");

-- CreateIndex
CREATE INDEX "CashAllocationRequest_employeeId_status_idx" ON "CashAllocationRequest"("employeeId", "status");

-- CreateIndex
CREATE INDEX "CashAllocationRequest_status_idx" ON "CashAllocationRequest"("status");

-- CreateIndex
CREATE INDEX "RewardCase_payoutPeriod_idx" ON "RewardCase"("payoutPeriod");

-- AddForeignKey
ALTER TABLE "PayrollLine" ADD CONSTRAINT "PayrollLine_runId_fkey" FOREIGN KEY ("runId") REFERENCES "PayrollRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PayrollLine" ADD CONSTRAINT "PayrollLine_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PayrollLineItem" ADD CONSTRAINT "PayrollLineItem_lineId_fkey" FOREIGN KEY ("lineId") REFERENCES "PayrollLine"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PayrollLineOverride" ADD CONSTRAINT "PayrollLineOverride_runId_fkey" FOREIGN KEY ("runId") REFERENCES "PayrollRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PayrollRunTotal" ADD CONSTRAINT "PayrollRunTotal_runId_fkey" FOREIGN KEY ("runId") REFERENCES "PayrollRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PayrollApprovalStep" ADD CONSTRAINT "PayrollApprovalStep_runId_fkey" FOREIGN KEY ("runId") REFERENCES "PayrollRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PayrollApprovalStep" ADD CONSTRAINT "PayrollApprovalStep_approverUserId_fkey" FOREIGN KEY ("approverUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EmployeeAdvance" ADD CONSTRAINT "EmployeeAdvance_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EmployeeAdvanceInstalment" ADD CONSTRAINT "EmployeeAdvanceInstalment_advanceId_fkey" FOREIGN KEY ("advanceId") REFERENCES "EmployeeAdvance"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EmployeeDeduction" ADD CONSTRAINT "EmployeeDeduction_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CashAllocationRequest" ADD CONSTRAINT "CashAllocationRequest_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ============================================================================================
-- Constraints Prisma cannot express, but which the module's correctness depends on.
-- ============================================================================================

-- At most ONE live payroll run per period. Cancelled runs are excluded so a period can be
-- re-run after a cancellation (revision 2, 3, ...), which is the only supported correction
-- path — there is deliberately no "un-approve".
CREATE UNIQUE INDEX "PayrollRun_period_active_key"
    ON "PayrollRun" ("period")
    WHERE "status" <> 'CANCELLED';

-- The post-approval freeze, at the database level.
--
-- The application already refuses to mutate an approved run in two places (a guard on every
-- endpoint, and the lockedAt/approvedAt checks). This is the third layer, and the only one that
-- survives a future developer writing a stray prisma.payrollLine.update(). Once the General
-- Manager has signed, the numbers are what they are.
CREATE OR REPLACE FUNCTION payroll_reject_change_after_approval() RETURNS trigger AS $$
DECLARE
    v_run_id  TEXT;
    v_approved TIMESTAMP(3);
BEGIN
    v_run_id := COALESCE(NEW."runId", OLD."runId");
    SELECT "approvedAt" INTO v_approved FROM "PayrollRun" WHERE "id" = v_run_id;
    IF v_approved IS NOT NULL THEN
        RAISE EXCEPTION
            'Payroll run % was approved on % and is frozen: % on % is not allowed.',
            v_run_id, v_approved, TG_OP, TG_TABLE_NAME
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "PayrollLine_freeze_after_approval"
    BEFORE UPDATE OR DELETE ON "PayrollLine"
    FOR EACH ROW EXECUTE FUNCTION payroll_reject_change_after_approval();

CREATE TRIGGER "PayrollRunTotal_freeze_after_approval"
    BEFORE UPDATE OR DELETE ON "PayrollRunTotal"
    FOR EACH ROW EXECUTE FUNCTION payroll_reject_change_after_approval();

-- PayrollLineItem has no runId of its own, so it resolves the run through its parent line.
CREATE OR REPLACE FUNCTION payroll_item_reject_change_after_approval() RETURNS trigger AS $$
DECLARE
    v_approved TIMESTAMP(3);
BEGIN
    SELECT r."approvedAt" INTO v_approved
      FROM "PayrollLine" l JOIN "PayrollRun" r ON r."id" = l."runId"
     WHERE l."id" = COALESCE(NEW."lineId", OLD."lineId");
    IF v_approved IS NOT NULL THEN
        RAISE EXCEPTION
            'The payroll run for line % was approved on % and is frozen: % is not allowed.',
            COALESCE(NEW."lineId", OLD."lineId"), v_approved, TG_OP
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "PayrollLineItem_freeze_after_approval"
    BEFORE UPDATE OR DELETE ON "PayrollLineItem"
    FOR EACH ROW EXECUTE FUNCTION payroll_item_reject_change_after_approval();
